src/Entity/Customer.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
#[ApiResource]
class Customer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $FirstName;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $LastName;

    #[ORM\Column(type: 'string', length: 200, nullable: true)]
    private $Email;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $Phone;

    #[ORM\Column(type: 'string', length: 200, nullable: true)]
    private $Address;

    #[ORM\OneToMany(mappedBy: 'CustomerID', targetEntity: Rental::class)]
    private $rentals;

    public function __construct()
    {
        $this->rentals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(?string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(?string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(?string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(?string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(?string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    /**
     * @return Collection<int, Rental>
     */
    public function getRentals(): Collection
    {
        return $this->rentals;
    }

    public function addRental(Rental $rental): self
    {
        if (!$this->rentals->contains($rental)) {
            $this->rentals[] = $rental;
            $rental->setCustomerID($this);
        }

        return $this;
    }

    public function removeRental(Rental $rental): self
    {
        if ($this->rentals->removeElement($rental)) {
            // set the owning side to null (unless already changed)
            if ($rental->getCustomerID() === $this) {
                $rental->setCustomerID(null);
            }
        }

        return $this;
    }
}

src/Entity/SemRegistre.php
<?php

namespace App\Entity;

use App\Repository\SemRegistreRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SemRegistreRepository::class)]
class SemRegistre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $civilite;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $intitule_poste;

    #[ORM\Column(type: 'string', length: 255)]
    private $phone;

    #[ORM\Column(type: 'string', length: 255)]
    private $phone_fix;

    #[ORM\Column(type: 'string', length: 255)]
    private $raison_soc;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse;

    #[ORM\Column(type: 'string', length: 255)]
    private $code_postale;

    #[ORM\Column(type: 'string', length: 255)]
    private $ville;

    #[ORM\Column(type: 'string', length: 255)]
    private $pays;

    #[ORM\Column(type: 'string', length: 255)]
    private $web_site;

    #[ORM\Column(type: 'string', length: 255)]
    private $activity;

    #[ORM\Column(type: 'string', length: 255)]
    private $etat_dem;

    #[ORM\OneToOne(inversedBy: 'semRegistre', targetEntity: User::class, cascade: ['persist', 'remove'])]
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getIntitulePoste(): ?string
    {
        return $this->intitule_poste;
    }

    public function setIntitulePoste(string $intitule_poste): self
    {
        $this->intitule_poste = $intitule_poste;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPhoneFix(): ?string
    {
        return $this->phone_fix;
    }

    public function setPhoneFix(string $phone_fix): self
    {
        $this->phone_fix = $phone_fix;

        return $this;
    }

    public function getRaisonSoc(): ?string
    {
        return $this->raison_soc;
    }

    public function setRaisonSoc(string $raison_soc): self
    {
        $this->raison_soc = $raison_soc;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostale(): ?string
    {
        return $this->code_postale;
    }

    public function setCodePostale(string $code_postale): self
    {
        $this->code_postale = $code_postale;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getWebSite(): ?string
    {
        return $this->web_site;
    }

    public function setWebSite(string $web_site): self
    {
        $this->web_site = $web_site;

        return $this;
    }

    public function getActivity(): ?string
    {
        return $this->activity;
    }

    public function setActivity(string $activity): self
    {
        $this->activity = $activity;

        return $this;
    }

    public function getEtatDem(): ?string
    {
        return $this->etat_dem;
    }

    public function setEtatDem(string $etat_dem): self
    {
        $this->etat_dem = $etat_dem;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

templates/admin_home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voiture index{% endblock %}

{% block body %}

  {% if is_granted('ROLE_ADMIN') %}

    <style>
      table {
        border: 1px solid black;
      }
    </style>

    <button onclick="window.print()">Print this page</button>
    <form action="{{path('envoie_email')}}" method="post">
      <table class="table">
        <tr>

          <th>
            N°</th>
          <th>Prenom</th>
          <th>Nom
          </th>
          <th>Email
          </th>
          <th>Téléphone</th>
          <th>Etat</th>
          <th></th>

        </tr>

        <tr>
          {% if liste_demande %}
            {% for demande in liste_demande %}
              <tr>
                <td>
                  <input type="checkbox" name="checked[]" value="{{demande.user.id}}" class="multi_checkbox checkall">
                  <td>{{demande.user.getNumRegister()}}</td>

                  <td>{{demande.nom}}</td>
                  <td>{{demande.prenom}}</td>
                  <td>{{demande.user.email}}</td>
                  <td>{{demande.phone}}</td>
                  <td>
                    <a href="{{path('show_dem',{'id':demande.id})}}">
                      show
                    </a>
                  </td>
                  {% if demande.getEtatDem == "en attente" %}

                    <td>
                      <a href="{{path('accepter',{'id':demande.id})}}">Accepter</a>
                      <a href="{{path('refuser',{'id':demande.id})}}">Refuser</a>
                    </td>
                  {% else %}
                    <td>
                      {{demande.getEtatDem}}</td>
                  {% endif %}
                </tr>

              {% endfor %}
            </table>

            <button type="submit">Envoyer email</button>

          </form>
        {% endif %}

      {% endif %}
    {% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}
				Car Rental Agency
			{% endblock %}
		</title>
		{% block stylesheets %}
			<link rel="stylesheet" href="https://bootswatch.com/4/litera/bootstrap.min.css">
			<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous"/>
		  <meta name="viewport" content="width=device-width, initial-scale=1.0">
		  
    {% endblock %}
	</head>
	<body>

		<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
			<a class="navbar-brand" href="#">Car Rental Agency</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="{{ path('home_admin')}}">Home
							<span class="sr-only">(current)</span>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ path('show_cars_admin') }}">Cars</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Contact</a>
					</li>
				</ul>
			</div>
		</nav>


		<div class="container pt-5"> {% block body %}{% endblock %}
			</div>
			{% block javascripts %}
						<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
			<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
			{% endblock %}
		</body>
	</html>

templates/email.html.twig
{% extends 'base.html.twig' %}

{% block title %}welcome
{% endblock %}

{% block body %}

  <h4>Cher
    {{user.firstName}}
    {{user.lastName}},
  </h4>

  <p>
    Nous serons heureux de vous acceuillir au salon Stratégie Clients, du 10 au 12 avril 2010 à Paris-Porte de Versailles.
  </p>
  <p>Pour faciliter votre accés à la manifestation, vous trouverez ci-dessous
    <strong>votre badge électronique.</strong>
  </p>

  <p>
    A l'entrée du salon, il vous suffira de
    <strong>scanner le code imprimé sur ce badge
    </strong>
    à l'aide des postes informatiques en self service prévus à cet effet ou bien en vous présentant directement à l'acceuil visiteur "spécial pré-enregistrée".
    <strong>Votre padge personnel sera imprimé sans attente !
    </strong><br>
    <strong>Attention: un seul badge sera imprimé par code .</strong>
  </p>
  <p>
    Votre numéro de badge est le :
    <strong>{{ user.getNumRegister()}}
      .
    </strong>
  </p>

{% endblock %}

templates/sem_registre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register{% endblock %}

{% block body %}
  {% include "javas.html.twig"%}

  <html>
    <head>
      <style>
        .entreprise,
        .vous {
          border: 1px solid black;
          margin: 60px;
          padding: 30px;

        }
      </style>

    </head>
    <body>
      {% if user.semRegistre %}
        <h1>
          vous êtes inscrit au séminaire
          <a href="{{path('show_profil')}}" class="btn btn-primary">Voir mon inscription
          </a>

        </h1>
      {% else %}
        <h2>S'inscire au séminaire
        </h2>
        <form method="post" action="{{path('sem_register')}}">
          <div class="vous">
            <div class="form-group">
              <label for="prenom">Prénom :
              </label>
              <input type="text" class="form-control" placeholder="Tapez votre prénom" name="prenom" required="required">
            </div>
            <div class="form-group">
              <label for="nom">Nom</label>
              <input type="nom" class="form-control" name="nom" placeholder="tapez votre nom" required="required">
            </div>

            <div class="form-group">
              <label for="civility">
                Civilté
              </label>
              <select class="form-control" name="civility" required="required">
                <option></option>
                <option>Madame
                </option>
                <option>
                  Mademoiselle</option>
                <option>
                  Monsieur</option>
              </select>
            </div>

            <div class="form-group">
              <label for="int_poste">Intitulé de poste
              </label>
              <input type="text" class="form-control" name="int_poste" required="required">
            </div>

            <div class="form-group">
              <label for="phone_fix">Téléphone Fixe</label>
              <input type="tel" class="form-control" name="phone_fix" required="required">
            </div>

            <div class="form-group">
              <label for="phone">Téléphone portable professionnel ou personnel à usage
              </label>
              <input type="tel" class="form-control" name="phone" required="required">
            </div>

            <small class="form-text text-muted">Votre numéro de téléphone servire uniquement à Weyou groupe , pour vous informer de tout changement (Horaires,Conférences,Report de derniére minute, envoir du badge, différentes, animations business et événements..) il ne sera en aucun cas communiqué aux exposants (badges, emailings, etc..)</small>
          </div>

          <div class="entreprise">
            <div class="form-group">
              <label for="raison">Raison Sociale
              </label>
              <input type="text" class="form-control" name="raison" required="required">
            </div>

            <div class="form-group">
              <label for="adresse">Adresse</label>
              <input type="text" class="form-control" name="adresse" required="required">
            </div>
            <div class="form-group">
              <label for="code_poste">
                Code Postale
              </label>
              <input type="text" class="form-control" name="code_poste" required="required">
            </div>

            <div class="form-group">
              <label for="ville">
                Ville</label>
              <input type="text" class="form-control" name="ville" required="required">
            </div>

            <div class="form-group">
              <label for="pays">
                Pays
              </label>
              <div id="pays"></div>
              <div class="form-group">
                <label for="web_site">
                  Site internet</label>
                <input type="text" class="form-control" name="web_site" required="required">
              </div>

            </div>
            <div class="form-group">
              <label for="activity">
                Activité</label>
              <input type="text" class="form-control" name="activity" required="required">
            </div>

          </div>

          <input type="submit" value="Enregistrer" class="btn-group-lg btn-success">
        </div>
      </div>
    {% endif %}
  {% endblock %}

templates/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SemRegistre{% endblock %}

{% block body %}
  <h1>Informations de condidat
  </h1>

  <table class="table">
    <tbody>

      <tr>
        <th>Civilite</th>
        <td>{{ sem_registre.civilite }}</td>
      </tr>
      <tr>
        <th>Nom</th>
        <td>{{ sem_registre.nom }}</td>
      </tr>
      <tr>
        <th>Prenom</th>
        <td>{{ sem_registre.prenom }}</td>
      </tr>
      <tr>
        <th>Intitule_poste</th>
        <td>{{ sem_registre.intitulePoste }}</td>
      </tr>
      <tr>
        <th>Phone</th>
        <td>{{ sem_registre.phone }}</td>
      </tr>
      <tr>
        <th>Phone_fix</th>
        <td>{{ sem_registre.phoneFix }}</td>
      </tr>
      <tr>
        <th>Raison_soc</th>
        <td>{{ sem_registre.raisonSoc }}</td>
      </tr>
      <tr>
        <th>Adresse</th>
        <td>{{ sem_registre.adresse }}</td>
      </tr>
      <tr>
        <th>Code_postale</th>
        <td>{{ sem_registre.codePostale }}</td>
      </tr>
      <tr>
        <th>Ville</th>
        <td>{{ sem_registre.ville }}</td>
      </tr>
      <tr>
        <th>Pays</th>
        <td>{{ sem_registre.pays }}</td>
      </tr>
      <tr>
        <th>Web_site</th>
        <td>{{ sem_registre.webSite }}</td>
      </tr>
      <tr>
        <th>Activity</th>
        <td>{{ sem_registre.activity }}</td>
      </tr>
      <tr>
        <th>Etat_dem</th>
        <td>{{ sem_registre.etatDem }}</td>
      </tr>
    </tbody>
  </table>

  {% if is_granted('ROLE_ADMIN') %}
    <a href="{{path('home')}}">
      retour à la liste
    </a>
  {% endif %}

{% endblock %}

templates/user_home.html.twig
{% extends 'base.html.twig' %}

{% block title %}welcome
{% endblock %}

{% block body %}
  <a href="{{path('sem_register')}}" class="btn btn-primary">
    S'inscrire au séminaire
  </a>

{% endblock %}